name: run pytest

on:
  pull_request:
    branches:["main"]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: Setuo Python
        user: actions/setup-python@v5
        with: 
          python-version: 3.13
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run pytest
