name: run pytest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      DB_USER: "postgres"

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: 3.12
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: python -m pytest -q

      - name: Failure Log
        if: failure()
        run: echo "1つ前のstepは失敗しました"

      - name: Print DB_USER
        run: echo "DB_USER -> ${DB_USER}"

      - name: Get Time
        id: get_time
        run: echo "time=$(date)" >> $GETHUB_OUTPUT

      - name: Print gethub output
        run: echo "1つ前のstepの出力は${{steps.get_time.outputs.time}}"です
        